import type {Metadata} from 'next'
import {Abril_Fatface, Roboto, Caveat, Roboto_Serif} from 'next/font/google'
import './globals.css'
import Provider from '@/lib/Provider'
import React, {ReactNode} from 'react'
import Footer from '@/components/Footer/Footer'
import Header from '@/components/Header/Header'

const abrilFatface = Abril_Fatface({
  subsets: ['latin'],
  weight: '400'
})

const caveat = Caveat({
  subsets: ['latin'],
  weight: ['400', '500', '700']
})

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['300', '400', '500', '700']
})

const robotoSerif = Roboto_Serif({
  subsets: ['latin'],
  weight: ['300', '400', '500', '700']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({children}: { children: ReactNode }) {
  return (
    <html lang="en">
    <body className={`${robotoSerif.className} ${abrilFatface.className} ${roboto.className} ${caveat.className}`}>
    <Provider>
      <div className={'body'}>
        <Header/>
        <main>{children}</main>
        <footer><Footer/></footer>
      </div>
    </Provider>
    </body>
    </html>
  )
}
