import Footer from '@/components/Footer/Footer'
import Header from '@/components/Header/Header'
import Provider from '@/lib/Provider'
import type { Metadata } from 'next'
import { ReactNode } from 'react'
import './globals.css'
import { useFontsHook } from '../hooks/useFontsHook'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  const { abrilFatface, robotoSerifRegular, caveatRegular, robotoRegular } =
    useFontsHook()

  return (
    <html lang='en'>
      <body
        className={`${robotoSerifRegular.variable} ${abrilFatface.variable} ${caveatRegular.variable} ${robotoRegular.variable}`}
      >
        <Provider>
          <div className={'body'}>
            <Header />
            <main>{children}</main>
            <footer>
              <Footer />
            </footer>
          </div>
        </Provider>
      </body>
    </html>
  )
}
